---

- name: Create temporary installer dir
  become: true
  ansible.builtin.file:
    path: "{{ installer.target_directory }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Get and extract installer
  become: true
  ansible.builtin.unarchive:
    src: "{{ installer.url }}"
    dest: "{{ installer.target_directory }}"
    remote_src: true
    owner: "root"
    group: "root"
    mode: "0755"
    creates: "{{ installer.target_directory }}/{{ installer.package_sub_dir }}"
  register: unarchive_result
  until: unarchive_result is succeeded
  retries: 3
  delay: 3

...
